### ISSUE TITLE
Version 11.0

### ISSUE THREAD

**Issue by foutoucour** [hibou-io/odoo-website-project#3]
Hey guys!

This module is awesome and we would like to use it in odoo 11.

Is the migration in your roadmap? Maybe we can share the effort?

Jr

**Comment by jaredkipe** [comment]
I just got my 11.0 database migration from Odoo, so I will be porting this and other modules we use internally in the very near future.

But keep your eyes on https://github.com/hibou-io/hibou-odoo-suite as we will be moving it there when we do so.

Thanks!

**Comment by foutoucour** [comment]
Thank you.

I will follow the hibou-odoo-suite too then!

**Comment by jaredkipe** [comment]
I've finished upgrading this, as well as adding a handful of new modules you might like for 11.0. 

https://github.com/hibou-io/hibou-odoo-suite/commits/11.0
